from pathlib import Path
from setuptools import find_packages
from setuptools import setup


version = "3.1.6.dev0"
long_description = (
    f"{Path('README.rst').read_text()}\n{Path('CHANGES.rst').read_text()}"
)


setup(
    name="collective.taxonomy",
    version=version,
    description="Create, edit and use hierarchical taxonomies in Plone!",
    url="https://pypi.org/project/collective.taxonomy/",
    long_description=long_description,
    classifiers=[
        "Development Status :: 6 - Mature",
        "Environment :: Web Environment",
        "Framework :: Plone",
        "Framework :: Plone :: 6.0",
        "Framework :: Plone :: 6.1",
        "Framework :: Plone :: Addon",
        "Framework :: Zope",
        "Framework :: Zope :: 5",
        "License :: OSI Approved :: GNU General Public License v2 or later (GPLv2+)",
        "Programming Language :: Python",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
    ],
    keywords="plone taxonomy dexterity",
    author="Bo Simonsen and Malthe Borch",
    author_email="bo@headnet.dk",
    license="GPLv2+",
    packages=find_packages("src"),
    package_dir={"": "src"},
    namespace_packages=["collective"],
    include_package_data=True,
    zip_safe=False,
    python_requires=">=3.8",
    install_requires=[
        "setuptools",
        "Acquisition",
        "BTrees",
        "Missing",
        "OFS",
        "Products.CMFCore",
        "Products.GenericSetup",
        "Products.ZCatalog",
        "collective.collectionfilter",
        "lxml",
        "persistent",
        "plone.api",
        "plone.app.contentmenu",
        "plone.app.contenttypes",
        "plone.app.multilingual",
        "plone.app.registry",
        "plone.app.vocabularies",
        "plone.autoform",
        "plone.base",
        "plone.behavior",
        "plone.dexterity",
        "plone.i18n",
        "plone.indexer",
        "plone.memoize",
        "plone.namedfile",
        "plone.protect",
        "plone.registry",
        "plone.restapi",
        "plone.supermodel",
        "z3c.form",
        "zExceptions",
        "zope.component",
        "zope.globalrequest",
        "zope.i18n",
        "zope.interface",
        "zope.lifecycleevent",
        "zope.publisher",
        "zope.schema",
        "zope.security",
        "zope.traversing",
    ],
    extras_require={
        "dev": [
            "zest.releaser[recommended]",
        ],
        "test": [
            "collective.MockMailHost",
            "plone.app.dexterity",
            "plone.app.iterate",
            "plone.app.querystring",
            "plone.app.robotframework",
            "plone.app.testing",
            "plone.browserlayer",
            "plone.schemaeditor",
            "plone.testing",
            "requests",
            "robotsuite",
            "transaction",
            "zope.event",
        ],
    },
    entry_points="""
    [z3c.autoinclude.plugin]
    target = plone
    """,
)
